### ISSUE TITLE
Filter by Store

### ISSUE THREAD

**Issue by ayeso** [ammobinDOTca/ammobin-client#95]
Having the ability to filter by store would be a nice benefit. Sometimes I know shipping costs are high so I want to compare only the local options. Right now I have to expand a bunch of the cheapest ones to see if its in a local store.

**Comment by nexus-uw** [comment]
@ayeso , would being able to filter by province be more or less helpful for your use case ?

**Comment by ayeso** [comment]
Yeah that would work too! I just know I get excited only to realize its in ontario and shipping makes it not worthwhile. Other than that fantastic site! I had been using google sheets pulling from cabelas haha
